heat_template_version: 2018-03-02
description: Portfolio template

resources:
  my_instance:
    type: OS::Nova::Server
    properties:
      flavor: gx3.1c3r
      image: Ubuntu Server 22.04 (Jammy) amd64 20220518
      key_name: Portfolio-Keypair
      name: Portfolio-Frontend-Instance
      networks:
        - network: Portfolio-Network

  my_instance_2:
    type: OS::Nova::Server
    properties:
      flavor: gx3.1c3r
      image: Ubuntu Server 22.04 (Jammy) amd64 20220518
      key_name: Portfolio-Keypair
      name: Portfolio-Backend-Instance
      networks:
        - network: Portfolio-Network