name: Update OpenStack Stack

on:
  push:
    branches:
      - main
    paths:
      - template.yaml

jobs:
  update-openstack-stack:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install OpenStack CLI and Heat Client
        run: |
          sudo apt update
          sudo apt install -y python3-openstackclient
          pip install python-heatclient
          pip install python-openstackclient

      - name: Authenticate with OpenStack
        env:
          OS_AUTH_URL: ${{ secrets.OS_AUTH_URL }}
          OS_PROJECT_ID: ${{ secrets.OS_PROJECT_ID }}
          OS_USERNAME: ${{ secrets.OS_USERNAME }}
          OS_PASSWORD: ${{ secrets.OS_PASSWORD }}
          OS_REGION_NAME: ${{ secrets.OS_REGION_NAME }}
          OS_USER_DOMAIN_NAME: ${{ secrets.OS_USER_DOMAIN_NAME }}
          OS_INTERFACE: ${{ secrets.OS_INTERFACE }}
          OS_IDENTITY_API_VERSION: ${{ secrets.OS_IDENTITY_API_VERSION }}
        run: echo "Authenticated with OpenStack"

      - name: Debug OpenStack Connection
        env:
          OS_AUTH_URL: ${{ secrets.OS_AUTH_URL }}
        run: |
          echo "Testing connectivity to OpenStack authentication URL..."
          curl -v $OS_AUTH_URL || echo "Could not reach OpenStack authentication URL"

      - name: Test OpenStack Authentication
        env:
          OS_AUTH_URL: ${{ secrets.OS_AUTH_URL }}
          OS_PROJECT_ID: ${{ secrets.OS_PROJECT_ID }}
          OS_USERNAME: ${{ secrets.OS_USERNAME }}
          OS_PASSWORD: ${{ secrets.OS_PASSWORD }}
          OS_REGION_NAME: ${{ secrets.OS_REGION_NAME }}
          OS_USER_DOMAIN_NAME: ${{ secrets.OS_USER_DOMAIN_NAME }}
          OS_INTERFACE: ${{ secrets.OS_INTERFACE }}
          OS_IDENTITY_API_VERSION: ${{ secrets.OS_IDENTITY_API_VERSION }}
        run: |
          echo "Attempting to issue a token..."
          openstack token issue || echo "Failed to authenticate with OpenStack"

      - name: Update Stack in OpenStack
        env:
          OS_AUTH_URL: ${{ secrets.OS_AUTH_URL }}
          OS_PROJECT_ID: ${{ secrets.OS_PROJECT_ID }}
          OS_USERNAME: ${{ secrets.OS_USERNAME }}
          OS_PASSWORD: ${{ secrets.OS_PASSWORD }}
          OS_REGION_NAME: ${{ secrets.OS_REGION_NAME }}
          OS_USER_DOMAIN_NAME: ${{ secrets.OS_USER_DOMAIN_NAME }}
          OS_INTERFACE: ${{ secrets.OS_INTERFACE }}
          OS_IDENTITY_API_VERSION: ${{ secrets.OS_IDENTITY_API_VERSION }}
        run: |
          echo "Updating OpenStack stack..."
          openstack stack update --template template.yaml Portfolio-Stack || echo "Failed to update the stack"

